[build-system]
requires = ["setuptools>=80.10.2", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cap-mcp"
dynamic = ["version"]
description = "CAP MCP: Model Context Protocol server for codebase awareness"

authors = [{name = "Domas Leščinskas", email = "domas.lescinskas@gmail.com"}]
license = {text = "Apache-2.0"}

keywords = ["ai", "mcp", "model-context-protocol", "codebase", "llm", "tools"]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",

    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Documentation",
    "Topic :: Communications",

    "License :: OSI Approved :: Apache Software License",

    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",

    "Operating System :: OS Independent",
]

requires-python = ">=3.10"
dependencies = [
    "cap-core==0.1.0",
    "mcp[cli]>=1.26.0",
]

[project.urls]
"Homepage" = "https://github.com/domasles/cap"
"Bug Reports" = "https://github.com/domasles/cap/issues"
"Source" = "https://github.com/domasles/cap"
"Documentation" = "https://github.com/domasles/cap#readme"

[tool.setuptools.dynamic]
version = {attr = "cap_mcp.meta.__version__"}

[tool.setuptools.packages.find]
where = ["."]
include = ["cap_mcp*"]
